//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleEFCodeFirst.Repositories
{
    [System.ComponentModel.DataAnnotations.Schema.Table("BinhLuan")]
    public partial class BinhLuan
    {
        [Key]
        [Display(Name = "Mã bình luận")]
        public int MaBL { get; set; }
        [Display(Name = "Mã sản phẩm")]
        [StringLength(1024)] public string MaSP { get; set; }
        [Display(Name = "Mã Khách Hàng")]
        [StringLength(1024)] public string MaKH { get; set; }
        [Display(Name = "Nội Dung Bình Luận")]
        [StringLength(1024)] public string NoiDung { get; set; }
        [Display(Name = "Ngày Đăng")]
        public Nullable<System.DateTime> NgayDang { get; set; }
        [Display(Name = "Họ Tên")]
        [StringLength(1024)] public string HoTen { get; set; }
        [Display(Name = "Email")]
        [StringLength(1024)] public string Email { get; set; }
        [Display(Name = "Đã trả lời")]
        [StringLength(1024)] public string DaTraLoi { get; set; }
        public Nullable<int> Parent { get; set; }
        [ForeignKey(nameof(MaKH))]
        public virtual AspNetUser AspNetUser { get; set; }
        [ForeignKey(nameof(MaSP))]
        public virtual SanPham SanPham { get; set; }
    }
}
