//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConsoleEFCodeFirst.Repositories
{
    [System.ComponentModel.DataAnnotations.Schema.Table("HangSanXuat")]
    public partial class HangSanXuat
    {
        public HangSanXuat()
        {
            this.SanPhams = new List<SanPham>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        [Display(Name = "Hãng sản xuất")]
        [StringLength(1024)] public string HangSX { get; set; }
        [Display(Name = "Tên Hãng")]
        [StringLength(1024)] public string TenHang { get; set; }
        [Display(Name = "Trụ sở chính")]
        [StringLength(1024)] public string TruSoChinh { get; set; }
        [Display(Name = "Quốc gia")]
        [StringLength(1024)] public string QuocGia { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
