//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleEFCodeFirst.Repositories
{
    [System.ComponentModel.DataAnnotations.Schema.Table("Sanphamcanmua")]
    public partial class Sanphamcanmua
    {
        public Sanphamcanmua()
        {
            this.DanhsachdangkisanphamNCCs = new List<DanhsachdangkisanphamNCC>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        public int ID { get; set; }
        [StringLength(1024)] public string MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }

        [StringLength(1024)] public string Mota { get; set; }
        [ForeignKey(nameof(MaSP))]
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<DanhsachdangkisanphamNCC> DanhsachdangkisanphamNCCs { get; set; }
    }
}
