//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleEFCodeFirst.Repositories
{
    [System.ComponentModel.DataAnnotations.Schema.Table("SanPhamKhuyenMai")]
    public partial class SanPhamKhuyenMai
    {
        [Key, Column(Order = 0)]
        [StringLength(1024)] public string MaKM { get; set; }
        [Key, Column(Order = 1)]
        [StringLength(1024)] public string MaSP { get; set; }

        [StringLength(1024)] public string MoTa { get; set; }
        public Nullable<int> GiamGia { get; set; }
        [ForeignKey(nameof(MaKM))]
        public virtual KhuyenMai KhuyenMai { get; set; }
        [ForeignKey(nameof(MaSP))]
        public virtual SanPham SanPham { get; set; }
    }
}
