//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
   
    [Table("ConfigAPI")]
    public partial class ConfigAPI
    {
        [Key]
        public int ID { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string MaNCC { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string LinkRequesrToken { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string LinkAccessToken { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string LinkKiemTraLuongTon { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string LinkXacNhanGiaoHang { get; set; }
        [ForeignKey(nameof(MaNCC))]
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
