//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("NhaCungCap")]
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.HopDongNCCs = new List<HopDongNCC>();
            this.Oauths = new List<Oauth>();
            this.ConfigAPIs = new List<ConfigAPI>();
            this.DanhsachdangkisanphamNCCs = new List<DanhsachdangkisanphamNCC>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string MaNCC { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string TenNCC { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string DiaChi { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string SDT_NCC { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Email { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Website { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Net_user { get; set; }
    
        public virtual ICollection<HopDongNCC> HopDongNCCs { get; set; }
        public virtual ICollection<Oauth> Oauths { get; set; }
        [ForeignKey(nameof(Net_user))]
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<ConfigAPI> ConfigAPIs { get; set; }
        public virtual ICollection<DanhsachdangkisanphamNCC> DanhsachdangkisanphamNCCs { get; set; }
    }
}
