//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("Oauth")]
    public partial class Oauth
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string ID { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Consumer_key { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Callback { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Request_token { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Verifier_token { get; set; }
        public Nullable<System.DateTime> Date_comsumer { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string MaNCC { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(1024)] public string Token { get; set; }
        public Nullable<System.DateTime> ExpiresTime { get; set; }
        [ForeignKey(nameof(MaNCC))]
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
