//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EC_TH2012_J.Models.Domain.EfModels
{
    [System.ComponentModel.DataAnnotations.Schema.Table("ChiTietDonHang")]
    public partial class ChiTietDonHang
    {
        [Key]
        [Display(Name = "Mã đơn hàng")]
        public string MaDH { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public string MaSP { get; set; }
        [Display(Name = "Số Lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> ThanhTien { get; set; }
        [ForeignKey(nameof(MaDH))]
        public virtual DonHangKH DonHangKH { get; set; }
        [ForeignKey(nameof(MaSP))]
        public virtual SanPham SanPham { get; set; }
    }
}
