//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EC_TH2012_J.Models.Domain.EfModels
{
    [Table("ConfigAPI")]
    public partial class ConfigAPI
    {
        [Key]
        public int ID { get; set; }
        public string MaNCC { get; set; }
        public string LinkRequesrToken { get; set; }
        public string LinkAccessToken { get; set; }
        public string LinkKiemTraLuongTon { get; set; }
        public string LinkXacNhanGiaoHang { get; set; }
        [ForeignKey(nameof(MaNCC))]
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
