//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models.Domain.EfModels
{
    [System.ComponentModel.DataAnnotations.Schema.Table("Link")]
    public partial class Link
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int id { get; set; }
        public string Url { get; set; }
        public string Image { get; set; }
        public string Text { get; set; }
        public string Group { get; set; }
    }
}
