//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace EC_TH2012_J.Models.Domain.EfModels
{
    [System.ComponentModel.DataAnnotations.Schema.Table("SanPham")]
    public partial class SanPham
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.HopDongNCCs = new HashSet<HopDongNCC>();
            this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();
            this.ThongSoKyThuats = new HashSet<ThongSoKyThuat>();
            this.Sanphamcanmuas = new HashSet<Sanphamcanmua>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string LoaiSP { get; set; }
        [ForeignKey(nameof(LoaiSP))]
        public virtual LoaiSP LoaiSanPham { get; set; }
        public Nullable<int> SoLuotXemSP { get; set; }
        public string HangSX { get; set; }
        public string XuatXu { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        [AllowHtml]
        public string MoTa { get; set; }
        public string AnhDaiDien { get; set; }
        public string AnhNen { get; set; }
        public string AnhKhac { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> isnew { get; set; }
        public Nullable<bool> ishot { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }

        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [ForeignKey(nameof(HangSX))]
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual ICollection<HopDongNCC> HopDongNCCs { get; set; }
        public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }
        public virtual ICollection<ThongSoKyThuat> ThongSoKyThuats { get; set; }
        public virtual ICollection<Sanphamcanmua> Sanphamcanmuas { get; set; }
    }
}
