//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EC_TH2012_J.Models.Domain.EfModels
{
    [System.ComponentModel.DataAnnotations.Schema.Table("Trackingaction")]
    public partial class Trackingaction
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public string Username { get; set; }
        public string MaSP { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Ngaythuchien { get; set; }
    }
}
